### ISSUE TITLE
Explanation for the tables

### ISSUE THREAD

**Issue by qiuwei** [sberbank-ai/ner-bert#1]
Hi, what does "Total spans in test set"  mean in the tables?

BTW, i got similar results on conll2003 data.
It seems bert is not so effective for NER.

**Comment by king-menin** [comment]
1. Span is a concatination of the sequence: B_ORG, I_ORG, I_ORG => ORG. There are counting of this spans in the table. In all articles we can see metrics for IOB (as conll-2003, with B_ORG and so on).

2. For example Google achived with BERTLARGE 96.6 (dev set) 92.8 (test set) on conll-2003 (as we can see in their <a href="https://arxiv.org/pdf/1810.04805.pdf">paper</a>).
I think, that BERT is very effective and universal for all tasks :+1: .
