### ISSUE TITLE
No module named 'elmoformanylangs'

### ISSUE THREAD

**Issue by MNCTTY** [sberbank-ai/ner-bert#10]
Hello! How to solve this error? I can't just get this with pip install

It arises while I do the convertion of checkpoints:

> Traceback (most recent call last):
>   File "/home/jupyter/ner-bert-master/convert_tf_checkpoint_to_pytorch.py", line 27, in <module>
>     from modules.layers.bert_modeling import BertConfig, BertModel
>   File "/home/jupyter/ner-bert-master/modules/__init__.py", line 1, in <module>
>     from .train.train import NerLearner
>   File "/home/jupyter/ner-bert-master/modules/train/train.py", line 9, in <module>
>     from modules.models.released_models import released_models
>   File "/home/jupyter/ner-bert-master/modules/models/__init__.py", line 1, in <module>
>     from .bert_models import BertBiLSTMCRF, BertBiLSTMAttnCRF
>   File "/home/jupyter/ner-bert-master/modules/models/bert_models.py", line 1, in <module>
>     from modules.layers.encoders import *
>   File "/home/jupyter/ner-bert-master/modules/layers/encoders.py", line 3, in <module>
>     from .embedders import BertEmbedder
>   File "/home/jupyter/ner-bert-master/modules/layers/embedders.py", line 9, in <module>
>     from elmoformanylangs.modules.embedding_layer import EmbeddingLayer
> ModuleNotFoundError: No module named 'elmoformanylangs'

Also it arises when I do import 

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-3-ca691cec4318> in <module>
> ----> 1 from modules import BertNerData as NerData
> 
> ~/ner-bert-master/modules/__init__.py in <module>
> ----> 1 from .train.train import NerLearner
>       2 from .data.bert_data import BertNerData
>       3 from .models.bert_models import BertBiLSTMCRF
>       4 
>       5 
> 
> ~/ner-bert-master/modules/train/train.py in <module>
>       7 import json
>       8 from modules.data.bert_data import BertNerData
> ----> 9 from modules.models.released_models import released_models
>      10 
>      11 
> 
> ~/ner-bert-master/modules/models/__init__.py in <module>
> ----> 1 from .bert_models import BertBiLSTMCRF, BertBiLSTMAttnCRF
>       2 
>       3 
>       4 __all__ = ["BertBiLSTMCRF", "BertBiLSTMAttnCRF"]
> 
> ~/ner-bert-master/modules/models/bert_models.py in <module>
> ----> 1 from modules.layers.encoders import *
>       2 from modules.layers.decoders import *
>       3 from modules.layers.embedders import *
>       4 import abc
>       5 import sys
> 
> ~/ner-bert-master/modules/layers/encoders.py in <module>
>       1 from torch import nn
>       2 import torch
> ----> 3 from .embedders import BertEmbedder
>       4 
>       5 
> 
> ~/ner-bert-master/modules/layers/embedders.py in <module>
>       7 import json
>       8 from torch import nn
> ----> 9 from elmoformanylangs.modules.embedding_layer import EmbeddingLayer
>      10 from elmoformanylangs.frontend import Model
>      11 
> 
> ModuleNotFoundError: No module named 'elmoformanylangs'

**Comment by OmGraja** [comment]
install your requirements:
pip install -r ner-bert/requirements.txt
install ELMoForManyLangs using git clone:
git clone https://github.com/HIT-SCIR/ELMoForManyLangs.git
pip install -e ELMoForManyLangs/

Then it should be resolved!

**Comment by MNCTTY** [comment]
Thank you for answering, but it didn't work for me
It turns out that I have more specific problem that I thought.
I use Google Cloud Platform with Jupyter Notebook in browser and ssh console. So I've done installation in console, and it was successful, but for some reason it can't be imported in jupyter. I don't know why.

I tried to do installation from jupyter notebook directly (it is how I usually install modules here), but it fails _in importing_:
`!python /home/jupyter/ner-bert-master/ELMoForManyLangs-master/setup.py install`

> running install
> running bdist_egg
> running egg_info
> writing elmoformanylangs.egg-info/PKG-INFO
> writing dependency_links to elmoformanylangs.egg-info/dependency_links.txt
> writing requirements to elmoformanylangs.egg-info/requires.txt
> writing top-level names to elmoformanylangs.egg-info/top_level.txt
> reading manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
> writing manifest file 'elmoformanylangs.egg-info/SOURCES.txt'
> installing library code to build/bdist.linux-x86_64/egg
> running install_lib
> warning: install_lib: 'build/lib' does not exist -- no Python modules to install
> 
> creating build/bdist.linux-x86_64/egg
> creating build/bdist.linux-x86_64/egg/EGG-INFO
> copying elmoformanylangs.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying elmoformanylangs.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying elmoformanylangs.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying elmoformanylangs.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> copying elmoformanylangs.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
> zip_safe flag not set; analyzing archive contents...
> creating 'dist/elmoformanylangs-0.0.2-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
> removing 'build/bdist.linux-x86_64/egg' (and everything under it)
> Processing elmoformanylangs-0.0.2-py3.7.egg
> Removing /opt/anaconda3/lib/python3.7/site-packages/elmoformanylangs-0.0.2-py3.7.egg
> Copying elmoformanylangs-0.0.2-py3.7.egg to /opt/anaconda3/lib/python3.7/site-packages
> elmoformanylangs 0.0.2 is already the active version in easy-install.pth
> 
> Installed /opt/anaconda3/lib/python3.7/site-packages/elmoformanylangs-0.0.2-py3.7.egg
> Processing dependencies for elmoformanylangs==0.0.2
> Searching for overrides==1.9
> Best match: overrides 1.9
> Adding overrides 1.9 to easy-install.pth file
> 
> Using /opt/anaconda3/lib/python3.7/site-packages
> Searching for numpy==1.14.5
> Best match: numpy 1.14.5
> Adding numpy 1.14.5 to easy-install.pth file
> 
> Using /opt/anaconda3/lib/python3.7/site-packages
> Searching for h5py==2.8.0
> Best match: h5py 2.8.0
> Adding h5py 2.8.0 to easy-install.pth file
> 
> Using /opt/anaconda3/lib/python3.7/site-packages
> Searching for torch==1.0.0
> Best match: torch 1.0.0
> Adding torch 1.0.0 to easy-install.pth file
> Installing convert-caffe2-to-onnx script to /opt/anaconda3/bin
> Installing convert-onnx-to-caffe2 script to /opt/anaconda3/bin
> 
> Using /opt/anaconda3/lib/python3.7/site-packages
> Searching for six==1.12.0
> Best match: six 1.12.0
> Adding six 1.12.0 to easy-install.pth file
> 
> Using /opt/anaconda3/lib/python3.7/site-packages
> Finished processing dependencies for elmoformanylangs==0.0.2

`import elmoformanylangs`

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-4-a3f496c7ea1a> in <module>
> ----> 1 import elmoformanylangs
> 
> ModuleNotFoundError: No module named 'elmoformanylangs'



And I tried your code:

`!git clone https://github.com/HIT-SCIR/ELMoForManyLangs.git`

> Cloning into 'ELMoForManyLangs'...
> remote: Enumerating objects: 171, done.
> remote: Total 171 (delta 0), reused 0 (delta 0), pack-reused 171
> Receiving objects: 100% (171/171), 81.14 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (86/86), done.


`!pip install -e ELMoForManyLangs/`

> Obtaining file:///home/jupyter/ner-bert-master/examples/ELMoForManyLangs
> Requirement already satisfied: torch in /opt/anaconda3/lib/python3.7/site-packages (from elmoformanylangs==0.0.2) (1.0.0)
> Requirement already satisfied: h5py in /opt/anaconda3/lib/python3.7/site-packages (from elmoformanylangs==0.0.2) (2.8.0)
> Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.7/site-packages (from elmoformanylangs==0.0.2) (1.14.5)
> Requirement already satisfied: overrides in /opt/anaconda3/lib/python3.7/site-packages (from elmoformanylangs==0.0.2) (1.9)
> Requirement already satisfied: six in /opt/anaconda3/lib/python3.7/site-packages (from h5py->elmoformanylangs==0.0.2) (1.12.0)
> Installing collected packages: elmoformanylangs
>   Found existing installation: elmoformanylangs 0.0.2
>     Uninstalling elmoformanylangs-0.0.2:
>       Successfully uninstalled elmoformanylangs-0.0.2
>   Running setup.py develop for elmoformanylangs
> Successfully installed elmoformanylangs
> Traceback (most recent call last):
>   File "/opt/anaconda3/bin/pip", line 11, in <module>
>     sys.exit(main())
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/__init__.py", line 78, in main
>     return command.main(cmd_args)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 184, in main
>     timeout=min(5, options.timeout)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 79, in _build_session
>     insecure_hosts=options.trusted_hosts,
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/download.py", line 337, in __init__
>     self.headers["User-Agent"] = user_agent()
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/download.py", line 126, in user_agent
>     setuptools_version = get_installed_version("setuptools")
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 836, in get_installed_version
>     working_set = pkg_resources.WorkingSet()
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 562, in __init__
>     self.add_entry(entry)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 618, in add_entry
>     for dist in find_distributions(entry, True):
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1883, in find_eggs_in_zip
>     if metadata.has_metadata('PKG-INFO'):
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1402, in has_metadata
>     return self.egg_info and self._has(self._fn(self.egg_info, name))
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1757, in _has
>     return zip_path in self.zipinfo or zip_path in self._index()
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1634, in zipinfo
>     return self._zip_manifests.load(self.loader.archive)
>   File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1591, in load
>     mtime = os.stat(path).st_mtime
> FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.7/site-packages/elmoformanylangs-0.0.2-py3.7.egg'

**Comment by OmGraja** [comment]
after installing it you need to import it **As a local library**
try this:
import ELMoForManyLangs.elmoformanylangs as elmoformanylangs

**Comment by MNCTTY** [comment]
wow it works! thank you so much!!
by the way, how did you know about this fact?

**Comment by OmGraja** [comment]
My pleasure :)) 
I faced the same issue!
