### ISSUE TITLE
prev_label = ""  Error

### ISSUE THREAD

**Issue by chzuo** [sberbank-ai/ner-bert#15]
Hi,

I got an error when I run 

> data = NerData.create(train_path, valid_path, vocab_file)

> ~/Downloads/ner-bert-master/modules/data/bert_data.py in get_data(df, tokenizer, label2idx, max_seq_len, pad, cls2idx, is_cls, is_meta)
>     189             if label != "O":
>     190                 label = label.split("_")[1]
> --> 191                 if label == prev_label:
>     192                     prefix = "I_"
>     193                 prev_label = label
> 
> UnboundLocalError: local variable 'prev_label' referenced before assignment

And if I cancel the comment in line 187: prev_label ="", it turns out missing the 'I_O 'label

**Comment by king-menin** [comment]
Thanks, Fix in your code locally, plz :(.
