### ISSUE TITLE
The length of token sequence is different from tag sequence

### ISSUE THREAD

**Issue by lz-chen** [sberbank-ai/ner-bert#16]
Hi! Thank you for sharing this implementation. 
I am using it to train on a NER dataset in Norwegian. I wanted to store the model predictions in CONLL file format but encounter some issues with, I assume, token mapping in the input sequence.
Basically, I got the `tokens`, `y_true`, `y_pred` from function `get_bert_span_report()` in `plot_metrics.py`.
And I want to write the predictions into a file by:
```
def write_to_conll(tokens, y_true, y_pred, conll_fpath):
    assert len(tokens) == len(y_true) and len(y_true) == len(y_pred)
    with conll_fpath.open('a') as f:
        for sentence, y_t, y_p in zip(tokens, y_true, y_pred): 
            assert len(sentence) == len(y_t) and len(y_t) == len(y_p)     
            for i in range(len(sentence)):
                newline = '{}\t{}\t{}\n'.format(sentence[i], y_t[i], y_p[i])
                f.write(newline)
            f.write('\n')
```
The assertion `assert len(sentence) == len(y_t) ` fails. The length of token sequence is always longer than the length of tag sequence. For example:
```
['Dette', 'er', 'som', 'George', 'Orwells', 'nytale', ',', 'av', 'samme', 'logiske', 'gehalt', 'som', '"', 'fred', 'er', 'krig', '"', ',', '"', 'stillhet', 'er', 'larm', '"', ',', '"', 'lys', 'er', 'mørke', '"', '.']
['O', 'O', 'O', 'PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
['O', 'O', 'O', 'PER', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
# len(sentence)=30, len(y_t)=29, len(y_p)=29
['I', 'diktet', '"', 'Om', 'å', 'vokse', 'nedover', '"', 'skriver', 'Rolf', 'Jacobsen', ':']
['O', 'O', 'O', 'PROD', 'O', 'O', 'PER', 'O']
['O', 'O', 'O', 'PROD', 'O', 'O', 'PER', 'O']
# len(sentence)=12, len(y_t)=8, len(y_p)=8
```
What should I do to get the equal length of token sequence and tag sequence?

**Comment by king-menin** [comment]
if u mean get_bert_span_report, u get spans instead tokens. For example:
`from modules.utils.utils import bert_labels2tokens, tokens2spans`
`tokens, labels = bert_labels2tokens(dl, preds)`
`spans_true = tokens2spans(tokens, labels)`
`print(spans_true[0])`
And get the following output:
[('i would like to find a flight from', 'fromloc.city-name'), ('charlotte', 'toloc.city-name'), ('to', 'fromloc.city-name'), ('las vegas', 'round-trip'), ('that makes a stop in', 'fromloc.city-name'), ('st.', 'stoploc.city-name'), ('louis', 'O')]
As u can see it is not tokens. It is full extracted entity. If u wanna to get tokens use: `bert_labels2tokens`.

**Note**, tokenizer split sequence by spaces: `input_sent.split()` and pass that to bert tokenizer. If u want use another split, tokenize and concat by space: `" ".join(your_own_tokenize(input_sent))`

**Comment by lz-chen** [comment]
Thank you! `bert_labels2tokens` was what I needed.
