### ISSUE TITLE
UnicodeDecodeError on the vocab file

### ISSUE THREAD

**Issue by lucky630** [sberbank-ai/ner-bert#17]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3799: character maps to <undefined>

when passing the vocab file to NerData.create() getting unicode error
need to add something like this in the code to make it work
open(vocab_file,encoding='utf8').read()

**Comment by king-menin** [comment]
Working with the BERT vocab file is the reused code from pytorch-bert implementation. Can you ask me number of line and name of file with the error.
