### ISSUE TITLE
something wrong in bert_data.py?

### ISSUE THREAD

**Issue by sloth2012** [sberbank-ai/ner-bert#2]
![image](https://user-images.githubusercontent.com/4048815/50084929-8df8ef00-0233-11e9-85b7-b8286b19cc42.png)
in the `get_data` funciton, should variable cls be a list?

**Comment by sloth2012** [comment]
if that, cls2idx[cls] should be wrong.

the code is about in line 197 in `modules.data.bert_data`

**Comment by king-menin** [comment]
cls - is the label of class (usally str) or None if is_cls=False in get_data.
My bad is i didn't check any types of arguments.

PS. Maybe code should be simplify. But i think, that it works correctly (with right input data). If you have any suggestions of improving. Please, come on :).
