### ISSUE TITLE
FP16 and NVIDIA Apex support

### ISSUE THREAD

**Issue by Nic-Ma** [sberbank-ai/ner-bert#20]
Hi @king-menin ,

Do you support FP16 and NVIDIA Apex as the Pytorch BERT examples?
Thanks.

**Comment by king-menin** [comment]
You can rewrite train.py or try to replace learner.optimizer to your own favorite optimizer.

PS
I am alone on this project, so add FP16 was in my task list too, but I have many other task from bosses :-) If you can write, do merge request plz.

**Comment by Nic-Ma** [comment]
@king-menin 

Thanks, I will try to add FP16 support with NVIDIA Apex lib later.
