### ISSUE TITLE
a small bug in  `get_mean_max_metric` function

### ISSUE THREAD

**Issue by AaronHeee** [sberbank-ai/ner-bert#21]
Thanks so much for your super nice implementation of NER-BERT! I'm writing to report a small bug.

We use the `get_mean_max_metric` in `BERT-NER/modules/utils/plot_metrics.py` to calculate the metric results, which will determine whether to save model during training time.

However,  in this function, `[3 + m_idx]` in `[float(h.split("\n")[-2].split()[3 + m_idx]) for h in history]` should be `[2 + m_idx]`, in order to obtain the correct results of target metrics.

 Please fix this bug, thanks a lot!

**Comment by king-menin** [comment]
it depends from sklearn-crfsuite version
