### ISSUE TITLE
BIO vs IO

### ISSUE THREAD

**Issue by Ulitochka** [sberbank-ai/ner-bert#22]
Hello.

In your example (https://github.com/sberbank-ai/ner-bert/blob/master/examples/factrueval-nmt.ipynb) you are using bio markups.
But in code (bert_data.py (187)):
 

>       # prev_label = ""
        for idx_, (orig_token, label) in enumerate(zip(orig_tokens, labels)):
            # Fix BIO to IO as BERT proposed https://arxiv.org/pdf/1810.04805.pdf

            try:

you use io. how do you get the original markup after training?

**Comment by king-menin** [comment]
We can extract original labels by replace first token label to B-PER. For example:
I-O I-O I-PER I-PER I-O -> I-O I-O B-PER I-PER I-O

**Comment by Ulitochka** [comment]
If we have 2 entities?
I-O I-O I-PER I-PER I-PER I-PER I-O -> I-O I-O B-PER I-PER I-PER B-PER I-O

**Comment by king-menin** [comment]
I is fail for now, but this situation is very rare. You can return BIO markup.

**Comment by Ulitochka** [comment]
This Fix BIO to IO as BERT proposed https://arxiv.org/pdf/1810.04805.pdf - increases quality?

**Comment by king-menin** [comment]
For our inner tasks, BUT. I took the second place in <a href="https://github.com/dialogue-evaluation/AGRR-2019">AGGR-2019<a/> competition with BIO markup. SO u can pick code from <a href="https://github.com/king-menin/AGRR-2019">here</a> (with BIO).

**Comment by Ulitochka** [comment]
Ok, thanks!
