### ISSUE TITLE
Mistake in main_metrics

### ISSUE THREAD

**Issue by brickee** [sberbank-ai/ner-bert#28]
current_tag = current_token.split('_', 1)[-1]   # replace '-' with "_"
This bug will totoally change the evaluation result.

**Comment by king-menin** [comment]
Maby you are right. You can do pull request with changes or try to use from modules.analyze_utils.plot_metrics import get_bert_span_report for mesure results.
Code from modules/analyze_utils/main_metrics.py was used for evaluation of FactRuEval dataset.
