### ISSUE TITLE
No BERT Fine-Tuning?

### ISSUE THREAD

**Issue by pfecht** [sberbank-ai/ner-bert#3]
Thanks for the comprehensive examples in this repository. 

Please correct me if I'm wrong but from my understanding, the benefits of this repository rely on the replacement of ELMo embeddings with BERT embeddings. This seems to work just fine resulting in good improvements. However, it doesn't seem very intuitive to me since it misses the fine-tuning of BERT for the NER task.

Have you tried anything in this direction of fine-tuning BERT for NER? Or to express it differently: Why do you need an LSTM encoder as a wrapper around BERT encodings?

**Comment by king-menin** [comment]
we didn't implement of bert fine-tuning because there are too a lot of params for single gpu and this needs more time. But we are working on this. And we didn't achieve SOTA results without fine-tune bert :-( (but comparable).

**Comment by Nic-Ma** [comment]
Hi @king-menin ,

Have you guys implemented fine-tune of BERT for NER?
Thanks.

**Comment by king-menin** [comment]
See pytorch-bert-pretrained. They learns BERT.
