### ISSUE TITLE
This model use a lots of memory

### ISSUE THREAD

**Issue by EricAugust** [sberbank-ai/ner-bert#5]
Beside bert model,  after I train my model.
Load bert and trained model, also data, it need 4.5G, this is very large.
And during this situation, very hard to deploy online.
So is there anyway to reduce memory use?

**Comment by king-menin** [comment]
reduce number of your parametres ))

**Comment by king-menin** [comment]
only BERT embedder need about 2 G gpu memory (in eval mode, without any additional layers on top).

**Comment by EricAugust** [comment]
I only add one lstm layer with 256 hiden states and a crf layer.

**Comment by PaulZhangIsing** [comment]
it is the reality. Otherwise you have to reduce the parameters
