### ISSUE TITLE
No uploaded ckpts and data?

### ISSUE THREAD

**Issue by MNCTTY** [sberbank-ai/ner-bert#8]
Hi
Did I understand correctly that you don't have an intend to share checkpoints from decoders training, sharing these notebooks others to replicate your results?

Also, I really can't find anywhere data from FactRuEval corpus (not only in this repository). May be you can share a link where you've downloaded it?
I've found only opencorpora corpus on kaggle, but when I opened it, I've found out that there are no classic NER tags such as 'loc', 'per', etc. Only tags that are adj, verb and others.

**Comment by king-menin** [comment]
Sorry, i haven't any time for develop or share models and so on for now. In this repo no any data or models ^(.  Link for FactRuEval (Russian NER competition dataset): https://github.com/dialogue-evaluation/factRuEval-2016
